/**
 * Circle collaborator email guard.
 *
 * CLAUDE.md §16: "Circles are for human collaborator emails only; do not attempt Mind-to-Mind
 * Circle membership." The official client-library docs are equally explicit: "Circles accept
 * human collaborator emails only, not Mind @hellominds.ai addresses."
 *
 * This guard had no test until the risk became concrete: creating a Mind named "CollabOS"
 * produces the platform address `collabos@hellominds.ai`, which the builder now has in hand and
 * could easily paste into `COLLABORATOR_TEST_EMAIL`. That would attempt exactly the Mind-to-Mind
 * membership the spec forbids — so the rejection is pinned here, before any network call can
 * happen.
 */
import { describe, expect, it } from "vitest";

import { assertHumanCollaboratorEmail } from "../../src/lib/minds/client.ts";
import { CollabOsMindsError } from "../../src/lib/minds/errors.ts";

describe("rejects Mind platform addresses", () => {
  it("rejects the real Mind address for this project", () => {
    // The exact address generated by naming the Mind "CollabOS".
    expect(() => assertHumanCollaboratorEmail("collabos@hellominds.ai")).toThrow(
      /human collaborator/i,
    );
  });

  it("explains why, and names Mind-to-Mind membership as unsupported", () => {
    let thrown: unknown;
    try {
      assertHumanCollaboratorEmail("collabos@hellominds.ai");
    } catch (error) {
      thrown = error;
    }

    expect(thrown).toBeInstanceOf(CollabOsMindsError);
    const message = (thrown as CollabOsMindsError).message;
    expect(message).toContain("collabos@hellominds.ai");
    expect(message).toMatch(/Mind-to-Mind Circle membership is not a supported/i);
  });

  it("is not retryable — repeating it would never succeed", () => {
    try {
      assertHumanCollaboratorEmail("collabos@hellominds.ai");
      expect.unreachable("should have thrown");
    } catch (error) {
      expect((error as CollabOsMindsError).retryable).toBe(false);
    }
  });

  it.each([
    "another.mind@hellominds.ai",
    "CollabOS@HelloMinds.ai",
    "MIXED@HELLOMINDS.AI",
    "a@hellominds.ai",
  ])("rejects %s regardless of casing", (email) => {
    expect(() => assertHumanCollaboratorEmail(email)).toThrow();
  });
});

describe("accepts genuine human addresses", () => {
  it.each([
    "someone@company.com",
    "you+collab@yourdomain.co.uk",
    "first.last@sub.domain.org",
    "mira.chen@example.com",
  ])("accepts %s", (email) => {
    expect(() => assertHumanCollaboratorEmail(email)).not.toThrow();
  });

  it("accepts a domain that merely contains 'hellominds' without being it", () => {
    // The guard anchors on the domain ending, so a lookalike host is not over-blocked.
    expect(() =>
      assertHumanCollaboratorEmail("person@hellominds.example.com"),
    ).not.toThrow();
  });
});

describe("rejects malformed input before any network call", () => {
  it.each([
    ["empty string", ""],
    ["no @", "notanemail"],
    ["no domain", "user@"],
    ["no local part", "@domain.com"],
    ["no TLD", "user@domain"],
    ["contains a space", "user name@domain.com"],
  ])("rejects %s", (_label, email) => {
    expect(() => assertHumanCollaboratorEmail(email)).toThrow(
      /not a valid collaborator email/i,
    );
  });
});
